AlphaFold2.ipynb

An error occurs when I run the pipeline.
TypeError: get_templates() got an unexpected keyword argument 'hhr_hits'
template_featurizer.get_templates() expects the variable called "hits" https://github.com/deepmind/alphafold/blob/0bab1bf84d9d887aba5cfb6d09af1e8c3ecbc408/alphafold/data/templates.py#L842

Bug Fixed in #Gather input features, predict structure

---

beta/AlphaFold_wJackhmmer.ipynb

The MSA file generated by https://toolkit.tuebingen.mpg.de/tools/hhblits starts with '#A3M#'.  This raises an error in the parse_a3m module when a custom alignment is provided:
IndexError: list index out of range.
This fixes that little bug.
Best regards.
Enzo

A small bug fixed when a custom alignment is provided

---

colabfold/batch.py
colabfold_batch

The multimer did not work me for FASTA input until I did this change (copying from the csv block).
You can ignore colabfold_batch but would be useful to have similar script in the top directory for those running from the repo.

Support multimer for FASTA input format

---

colabfold/batch.py

Otherwise, batch.py cannot find the file in some running scenarios.

Use path to stereo_chemical_props.txt relative to batch.py

---

colabfold/batch.py

Typo, wrong variable for exporting the relaxed structure.

Fix typo - export right relaxed pdb

---

colabfold/batch.py

I am not 100% sure that this is a bug in `batch.py`. I _think_ the intent was to be able to model multimers with `.fasta` files formated like
```
>interesting_dimer
SEQUENCEA:SEQUENCEB
```
If this is the case, it was broken for dimeric complexes, but this pr should fix it. This has led to some confusion (see #97 for instance).

fix fasta multimer input in CLI

---

colabfold/batch.py

I tried to run colab batch on complexes, but got an error saying "[Errno 2] No such file or directory" at line 1147 in batch.py:
`result_zip.write(file, arcname=file.name` 
It looks like the run function was not properly accounting for files (pdbs and jsons) that were renamed during ranking (it was directly reading out the index in model_rank instead of using the value as a key). I switched to enumerate (matching syntax in predict_structure, line 304 in batch.py), and that fixed the problem.

fixed naming of files when making zip

---

setup_databases.sh

The `setup_databases.sh`  script may execute a command returning an error but the script would still continue, despite its intended design to stop  on any error.
The offending line is here: https://github.com/sokrypton/ColabFold/blob/b93680f62a305951cb7aa402903b34f595a6156a/setup_databases.sh#L23
`set +e` disables error checking but never turns it back on if download succeeded.
For example, the script may continue despite `mmseqs` being absent from the system or the wrong version is used, where `mmseqs` command(s) may silently not be properly executed, resulting in an incomplete database.
This PR restores correct behavior.

fix `setup_databases.sh` script silently continuing despite errors

---

colabfold/batch.py

It will resolve issues #191 and #181
I am not completely sure about which one would be the solution either this PR or
```python
if is_complex and (paired_msa is not None):
all_seq_features = build_multimer_feature(
paired_msa[sequence_index]
)
feature_dict.update(all_seq_features)
```
When I tested this PR on Colab, it worked fine though.

fixed a bug for pair_mode==unpaired 

---

colabfold/mmseqs/search.py
setup_databases.sh

Update the default UniRef database to [uniref30_2202.tar.gz](https://wwwuser.gwdg.de/~compbiol/colabfold/uniref30_2202.tar.gz) for local `colabfold_search`.

update uniref30db to 2202

---

colabfold/batch.py

Currently, the template search is not working if the input file format is a3m even though `--templates` arg was added. This PR fixes the issue.

turn on template search for a3m input files

---

README.md

Current conda python version 3.10 raises the following error during the installation:
```shell
ERROR: Could not find a version that satisfies the requirement tensorflow-cpu<2.8.0 (from colabfold[alphafold]) (from versions: 2.8.0, 2.8.1, 2.8.2, 2.9.0rc0, 2.9.0rc1, 2.9.0rc2, 2.9.0, 2.9.1)
ERROR: No matching distribution found for tensorflow-cpu<2.8.0
```

Update README.md to create a Python 3.7 environment

---

colabfold/batch.py

This PR seeks to fix the interaction between specifying templates while using an a3m. Natively this breaks when the a3m contains a multimeric protein. As an example, an a3m generated from the following fasta fails when using the --templates flag:
`> 1QYS_1_Chain A_TOP7_ComputationallyDesignedSequence
AQAQAQTG:DGTLAVPFKAQAQTG:LECYQCYGVPFETSCPSITCPYPDGVCVTQEAAVIVDSQTRKVKNNLCLPICPPNIESMEILGTKVNVKTSCCQEDLCNVAVP` 
The bug occurs because when using an a3m file as well as templates, template features are generated for only the concatenated sequence as opposed to the individual chains. This causes a mismatch in the `generate_input_feature` call as the length of `template_features` is 1 while `query_seqs_unique` will have length equal to the number of chains. 
This fix splits the concatenated …

fix a3m + template

---

colabfold/batch.py

Skip template search process when `--custom-template-path` flag is provided.
This PR was prepared in response to the following two proposals: https://github.com/sokrypton/ColabFold/issues/424 and https://github.com/sokrypton/ColabFold/pull/468

Skip template search when custom_template_path provided

---

colabfold/utils.py

In `CFMMCIFIO` (which is used by `convert_pdb_to_mmcif`), map the chain ID to the `_atom_site.label_asym_id`, which corresponds to `_struct_asym.id`.
Should fix https://github.com/sokrypton/ColabFold/issues/449 and https://github.com/sokrypton/ColabFold/issues/469
@data2code @jkosinski

Fix CFMMCIFIO _struct_asym.id values

---

colabfold/mmseqs/search.py

This introduces the environmental pairing strategy built upon SPIRE metagenomic database contig labels.
Addition of the database `spire_ctg10_2401_db` must be accompanied to run this feature properly.
My original intention was to set `--use-env-pairing 1` as a default parameter, however, I found it better to keep it zero until a proper establishment of this feature being made.

add environmental pairing feature

---

beta/omegafold.ipynb

The existing version of the OmegaFold notebook on the ColabFold repository doesn't work because of compatibility issues with biopython. Reverting to biopython 1.81 during installation fixes the issue. The maintainers would have to update the link to the colab notebook, so that this change can be reflected for those trying to run this on Google Colab.
The original line:
``%shell pip -q install py3Dmol biopython``
is updated to:
``%shell pip -q install py3Dmol biopython``
in the installation block of the OmegaFold notebook located at ColabFold/beta/omegafold.ipynb

Fixing biopython compatibility issue by reverting to 1.81

---

pyproject.toml

The <3.12 python version check was making it impossible to install the package on Linux distributions that use newer versions of python by default. Can confirm that the ColabFold package installs perfectly on current latest versions of python and the check in my opinion is unnecessary.

removed ,<3.12 for causing installation issues

---

pyproject.toml

This is a minimal PR changing `tensorflow-cpu -> tensorflow` in `pyproject.toml` as Tensorflow does not build wheels of tensorflow-cpu for Arm. 
See #637 for more details.
@milot-mirdita Do you think there is a better way to overcome thi?

Support `aarch64` with pip

---

MsaServer/config.json

Hi,
I raised this pull request based on the following:
- My own experience with deploying the MsaServer
- The GitHub issue here: https://github.com/sokrypton/ColabFold/issues/502
- The thread in this issue here: https://github.com/soedinglab/hh-suite/issues/362
- The GitHub issue I raised here: https://github.com/sokrypton/ColabFold/issues/533
Please let me know if you feel this breaks functionality, I am happy to adjust. This is what worked for setting up the MsaServer and running the AlphaFold2 notebook based on latest notes and code in main

Adjust configuration to use PDB100 instead of PDB70 database
